name: Run unit tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  init:
    name: Init before the fun stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - uses: gradle/gradle-build-action@v2

  jvm_unit_tests:
    name: JVM unit tests
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Run Unit Tests
        run: ./gradlew check

  instrumented_unit_tests:
    name: JVM unit tests
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Enable KVM group perms (for Android emulator)
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm

      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          disable-animations: true
          disk-size: 6000M
          heap-size: 600M
          script: ./gradlew connectedCheck

  screenshot_tests:
    name: Run screenshot tests
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Make sure Git LFS is tracking all the necessary files
        run: |
          ./.github/scripts/check-git-lfs.sh

      - name: Run Snapshot Tests
        run: ./gradlew verifyPaparazzi

  upload_reports:
    name: Run screenshot tests
    runs-on: ubuntu-latest
    needs: [jvm_unit_tests, instrumented_unit_tests, screenshot_tests]
    if: ${{ always() }}
    steps:
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Unit test results
          files: |
            **/build/test-results/**/TEST-*.xml
            **/build/**/androidTest-results/**/TEST-*.xml

      - name: Upload Failure Test Reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-reports
          path: |
            **/build/reports/*
